### ISSUE TITLE
About Hungarian matching loss?

### ISSUE THREAD

**Issue by sqlkrad** [lucidrains/slot-attention#1]
Hi, thanks for your great work! I wonder if Hungarian matching loss could be added to this package since set prediction is also an important part of this work.

**Comment by tkipf** [comment]
I am not the author of this repository, but you can use this scipy function to compute the Hungarian matching: https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.linear_sum_assignment.html

**Comment by sqlkrad** [comment]
Thank you so much!
