### ISSUE TITLE
RuntimeError on GPU

### ISSUE THREAD

**Issue by Alxead** [lucidrains/slot-attention#7]
When I run the code on GPU, I got the following error:

> RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

I think that it's because in line 43
 ```
slots = mu + sigma * torch.randn(mu.shape)
```
`torch.randn()` generate random numbers on CPU, but the `mu` and `sigma` are on GPU. So I get the this error.

**Comment by lucidrains** [comment]
@Alxead Hello Alex! Fixed in 1.1.1 - Thanks for reporting :)
