### ISSUE TITLE
Should we divide self.scale instead of multiplied self.scale for slot attention?

### ISSUE THREAD

**Issue by hding2455** [lucidrains/slot-attention#9]
In line 54 of slot_attention.py, should we use  

dots = torch.einsum('bsc,bnc-> bsn', q, k) / self.scale 

instead of 

dots = torch.einsum('bsc,bnc-> bsn', q, k) * self.scale 

for temperature normalization?

**Comment by deepsworld** [comment]
At https://github.com/lucidrains/slot-attention/blob/master/slot_attention/slot_attention.py#L11, it is already `-0.5`.

**Comment by hding2455** [comment]
Oh! Sorry for my silly mistake.
